---
  options:
    formatter: "stylish"
  rules:
    extends-before-mixins: 1
    extends-before-declarations: 1
    placeholder-in-extend: 1
    mixins-before-declarations: 0
    one-declaration-per-line: 1
    empty-line-between-blocks: 0
    single-line-per-selector: 1
    no-color-keywords: 1
    no-color-literals: 0
    no-css-comments: 1
    no-debug: 1
    no-duplicate-properties: 0
    no-empty-rulesets: 1
    no-extends: 0
    no-ids: 1
    no-important: 0
    no-invalid-hex: 1
    no-mergeable-selectors: 1
    no-misspelled-properties: 1
    no-qualifying-elements: 0
    no-trailing-zero: 1
    no-transition-all: 0
    no-url-protocols: 1
    no-vendor-prefixes: 0
    no-warn: 0
    force-attribute-nesting: 0
    force-element-nesting: 0
    force-pseudo-nesting: 0
    function-name-format: 1
    mixin-name-format: 1
    placeholder-name-format: 1
    variable-name-format:
      - 1
      -
        allow-leading-underscore: false
    border-zero: 1
    brace-style: 1
    clean-import-paths: 1
    empty-args: 1
    hex-length: 1
    hex-notation: 1
    indentation:
      - 2
      -
        size: 4
    leading-zero: 0
    nesting-depth:
      - 1
      - max-depth: 4
    property-sort-order: 0
    pseudo-element: 0
    quotes:
      - 1
      -
        style: "double"
    shorthand-values: 1
    url-quotes: 1
    variable-for-property: 1
    zero-unit: 1
    space-after-comma: 1
    space-before-colon: 1
    space-after-colon: 1
    space-before-brace: 1
    space-before-bang: 1
    space-after-bang: 1
    space-between-parens: 1
    trailing-semicolon: 1
    final-newline: 1
